#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: DevBlog de Seb
author:
  twitter: svermeille

# Short bio or description (displayed in the header)
description:
  en: Technology Enthusiast
  fr: Passionné de technologies

#translated texts
i18n:
  blog:
    en: Blog
    fr: Blog
  about:
    en: About
    fr: A Propos

navbar:
  en:
    howto:
      name: "Howto"
      url: "/howto"
    projects:
      name: "Projects"
      url: "/projects"
    blog:
      name: "Blog"
      url: "/blog"
    about:
      name: "About"
      url: "/about"
  fr:
    howto:
      name: "Tutoriaux"
      url: "/tutoriaux"
    projects:
      name: "Projets"
      url: "/projets"
    blog:
      name: "Blog"
      url: "/blog"
    about:
      name: "À propos"
      url: "/a-propos"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/4329594?v=3&s=55

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: sebastienvermeille
  instagram:
  linkedin: sebastienvermeille
  pinterest:
  rss: RSS # just type anything here for a working RSS icon
  twitter: svermeille_com
  stackoverflow: users/2398518/svermeille # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  slack: http://slackin.tavernedudev.fr


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: sebastien-vermeille-blog

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-91985102-2

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://sebastien.vermeille.blog

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

collections:
  howtos:
    output: true
  projects:
    output: true

defaults:
  -
    scope:
      path: "_posts"
      type: "post"
    values:
      permalink: "blog/:title"
  -
    scope:
      path: "_howtos"
      type: "howtos"
    values:
      permalink: "tutoriaux/:title"
  -
    scope:
      path: "_projects"
      type: "projects"
    values:
      permalink: "projets/:title"

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
 # style: :compressed # You might prefer to minify using :compressed

languages: ["en", "fr"]
exclude_from_localizations: ["javascript", "images", "css"]

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jemoji # Emojy support
  - jekyll-sitemap


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME